In [1]:
import pandas as pd
import numpy as np
from math import pi
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from os import listdir, mkdir
from os.path import isdir, join
import seaborn as sns

In [2]:
FEATURES_PATH = "feature_vectors2"
SHA_CSV_PATH = "sha256_family.csv"

In [3]:
paths = [f for f in listdir(FEATURES_PATH)][:25000]

In [4]:
len(paths)

25000

In [5]:
malwares = pd.read_csv(SHA_CSV_PATH, sep=",")
malwares.head(2)

                                              sha256       family
0  090b5be26bcc4df6186124c2b47831eb96761fcf61282d...     Plankton
1  bedf51a5732d94c173bcd8ed918333954f5a78307c2a2f...  DroidKungFu

In [6]:
import os
import pandas as pd
import datetime as dt
import glob

In [7]:
filename= pd.Series([file for file in glob.glob('../PFE/feature_vectors2/*')])

In [8]:
df1=pd.DataFrame(columns=['filename'])

df1.set_index('filename')

# I set filename list to df['filename']
df1['filename']= filename.str.slice(start=24)

In [9]:
df1

                                                 filename
0       00002d74a9faa53f5199c910b652ef09d3a7f6bd42b693...
1       000068216bdb459df847bfdd67dd11069c3c50166db1ea...
2       0000764713b286cfe7e8e76c7038c92312977712d9c5a8...
3       0000962c2c34de1ca0c329b18be7847459da2d9d14b6b2...
4       000167f1ff061ea91440c40659c11c2af160342fd2e493...
...                                                   ...
129008  fffcaa2b9c4490f0ebcfe27149e38b5cd132bc577de1e8...
129009  fffda9190ee6b853655c9894826d6e0b15047ffcc2f086...
129010  fffe775bb117bc7b4d0b9a689cace9e08955177de82118...
129011  ffff52336af65fdc0d58ed907d4a81a0acd250a9c16dc8...
129012  ffff64617c42e24fd1e572478279d547b834ef5e497f09...

[129013 rows x 1 columns]

In [10]:
malwares.rename(columns={"sha256": "filename"}, inplace = True)
malwares['Category']='Malware'
malwares

,filename,family,Category
0,090b5be26bcc4df6186124c2b47831eb96761fcf61282d...,Plankton,Malware
1,bedf51a5732d94c173bcd8ed918333954f5a78307c2a2f...,DroidKungFu,Malware
2,149bde78b32be3c4c25379dd6c3310ce08eaf58804067a...,Plankton,Malware
3,dd11c105ec8bb3c851f5955fa53eebb91b7dc46bef4d91...,GinMaster,Malware
4,6832234c4eae7a57be4f68271b7eecb056c4cd8352c67d...,FakeDoc,Malware
...,...,...,...
5555,21fabf2761a48807d648b333bf78c008172d4b8a048f61...,DroidKungFu,Malware
5556,1143ad4d60ebb152d5dbabf69f3e555676e7f62c598186...,GinMaster,Malware
5557,03d1161b5e4e76db43b9a484596b4524ac7e40a9b4fbba...,FakeInstaller,Malware
5558,7b40ede3642fc216b51ba07ada55bfb4db3c6de9df31b6...,GinMaster,Malware
5559,08811dd354c2c76c1bd3ad8e0c9fbecb60663442ce7b12...,Opfake,Malware

In [ ]:
df2 = pd.merge(df1, malwares, on='filename', how='left')

In [11]:
df2 = pd.concat([df1, malwares], ignore_index=True)

In [12]:
df2.drop(['family'], axis=1, inplace=True)

In [13]:
df2.fillna('Begnine', inplace=True)

In [14]:
df2

                                                 filename Category
0       00002d74a9faa53f5199c910b652ef09d3a7f6bd42b693...  Begnine
1       000068216bdb459df847bfdd67dd11069c3c50166db1ea...  Begnine
2       0000764713b286cfe7e8e76c7038c92312977712d9c5a8...  Begnine
3       0000962c2c34de1ca0c329b18be7847459da2d9d14b6b2...  Begnine
4       000167f1ff061ea91440c40659c11c2af160342fd2e493...  Begnine
...                                                   ...      ...
134568  21fabf2761a48807d648b333bf78c008172d4b8a048f61...  Malware
134569  1143ad4d60ebb152d5dbabf69f3e555676e7f62c598186...  Malware
134570  03d1161b5e4e76db43b9a484596b4524ac7e40a9b4fbba...  Malware
134571  7b40ede3642fc216b51ba07ada55bfb4db3c6de9df31b6...  Malware
134572  08811dd354c2c76c1bd3ad8e0c9fbecb60663442ce7b12...  Malware

[134573 rows x 2 columns]

In [15]:
from sklearn.model_selection import train_test_split
X = df2.filename
y = df2.Category
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
print("TRAIN:", X_train.index, "TEST:", X_test.index)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, shuffle=False)
print("TRAIN:", X_train.index, "VALIDATION:", X_val.index)

TRAIN: Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            107648, 107649, 107650, 107651, 107652, 107653, 107654, 107655,
            107656, 107657],
           dtype='int64', length=107658) TEST: Int64Index([107658, 107659, 107660, 107661, 107662, 107663, 107664, 107665,
            107666, 107667,
            ...
            134563, 134564, 134565, 134566, 134567, 134568, 134569, 134570,
            134571, 134572],
           dtype='int64', length=26915)
TRAIN: Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            107648, 107649, 107650, 107651, 107652, 107653, 107654, 107655,
            107656, 107657],
           dtype='int64', length=107658) VALIDATION: Int64Index([107658, 107659, 107660, 107661, 107662, 107663, 107664, 107665,
            107666, 107667,
            ...
            134563, 134564, 134565, 134566, 134567, 134568, 134569, 134570,
            134571, 134572],
           dtype='int64', length=26915)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
print("TRAIN:", X_train.index, "TEST:", X_test.index)

TRAIN: Int64Index([ 94615,  89351, 118079,  85542,  55792,  17658,  52325,    990,
              7653,  49312,
            ...
             21058,    756,  75529,  16329,  22454,  65203,  17470,  77004,
            116827, 122474],
           dtype='int64', length=107658) TEST: Int64Index([ 99382, 126415,  60978,  73944,  93144, 111254,  39756,  65003,
             59045,   1604,
            ...
             26190,   1032,  78538,  19322,  32249,   4540,  35048,  16557,
             25087, 108709],
           dtype='int64', length=26915)

In [18]:
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [     0      1      2 ... 134570 134571 134572] TEST: [    21     23     26 ... 134549 134562 134568]
TRAIN: [     0      1      2 ... 134570 134571 134572] TEST: [     7     11     15 ... 134553 134554 134563]
TRAIN: [     1      2      3 ... 134569 134570 134572] TEST: [     0     14     20 ... 134555 134560 134571]
TRAIN: [     0      1      2 ... 134570 134571 134572] TEST: [     3      5     91 ... 134537 134558 134561]
TRAIN: [     0      1      3 ... 134570 134571 134572] TEST: [     2      4      9 ... 134509 134519 134528]
TRAIN: [     0      2      3 ... 134569 134570 134571] TEST: [     1     19     27 ... 134566 134567 134572]
TRAIN: [     0      1      2 ... 134569 134571 134572] TEST: [     6     10     22 ... 134557 134559 134570]
TRAIN: [     0      1      2 ... 134570 134571 134572] TEST: [    16     37     59 ... 134527 134538 134543]
TRAIN: [     0      1      2 ... 134570 134571 134572] TEST: [    12     54     60 ... 134529 134541 134569]
TRAIN: [     0      1      2 ... 134570 134571 134572] TEST: [     8     17     30 ... 134548 134564 134565]

In [19]:
from sklearn.model_selection import StratifiedKFold, train_test_split

class StratifiedKFold3(StratifiedKFold):

    def split(self, X, y, groups=None):
        s = super().split(X, y, groups)
        for train_indxs, test_indxs in s:
            y_train = y[train_indxs]
            train_indxs, cv_indxs = train_test_split(train_indxs,stratify=y_train, test_size=(1 / (self.n_splits - 1)))
            yield train_indxs, cv_indxs, test_indxs

In [43]:
X = df2.filename
y = df2.Category
g = StratifiedKFold3(10).split(X,y)
train, cv, test = next(g)
train.shape, cv.shape, test.shape

((107657,), (13458,), (13458,))

In [44]:
train

array([117956, 134340, 105307, ...,  41762,  64225, 118844])

In [45]:
df_train = pd.DataFrame(data=train, index= None, columns=["index"])
df_train

         index
0       117956
1       134340
2       105307
3       114578
4        83915
...        ...
107652  103683
107653   70818
107654   41762
107655   64225
107656  118844

[107657 rows x 1 columns]

In [41]:
df2 = df2.rename_axis('index').reset_index()
df2

ValueError: cannot insert index, already exists

In [24]:
df_train = df_train.merge(df2, on = 'index')

In [25]:
df_train

         index                                           filename Category
0        63963  7e936d4dcfb05ca84b04134aefc4ef5549626c6fa234f7...  Begnine
1        94044  b9e622131768f0a26fe0bf19f8db4d44d7f86fce7508b9...  Begnine
2       125328  f8ba0591830da5144d207bdfa2de38346bb4d447aabeeb...  Begnine
3       121676  f14f03805dd42c0f61c0f8689284c7ad9dd2e25676378e...  Begnine
4        82664  a36a718cfc18d68b612581d31bc5bca59c5cfc80bb84f2...  Begnine
...        ...                                                ...      ...
107652   98312  c27e0f17755104b04197c5274dcbeb5d0c65ede6ea0a6b...  Begnine
107653   20488  2812ba9bd3d4ae2361d861c0da7d21f3367c1c28cd8e74...  Begnine
107654  130740  b20766395516162f7a4cc42d822eff3712a62582e734c1...  Malware
107655   89803  b180932b51c95d6e0a96b8cf058cc8463e1a501991eed5...  Begnine
107656   36815  486114ae6ac1f8f2f7140a54a920ce8e2628d99e49f70f...  Begnine

[107657 rows x 3 columns]

In [26]:
df_train.to_csv("strat_train_1.csv", columns= ['filename', 'Category'], index=False)

In [27]:
df_test = pd.DataFrame(data=test, index= None, columns=["index"])
df_test = df_test.merge(df2, on = 'index')
df_test

        index                                           filename Category
0           0  00002d74a9faa53f5199c910b652ef09d3a7f6bd42b693...  Begnine
1           1  000068216bdb459df847bfdd67dd11069c3c50166db1ea...  Begnine
2           2  0000764713b286cfe7e8e76c7038c92312977712d9c5a8...  Begnine
3           3  0000962c2c34de1ca0c329b18be7847459da2d9d14b6b2...  Begnine
4           4  000167f1ff061ea91440c40659c11c2af160342fd2e493...  Begnine
...       ...                                                ...      ...
13453  129564  5202b2598b601be7d693fd524bbf22a81398c09bf38367...  Malware
13454  129565  9ad23e451055a06126e3e42435458e4209a730d7cef574...  Malware
13455  129566  9ce927e9d8562211a6287dce9414f8b86efd3727179d0a...  Malware
13456  129567  30f70d65b05da36bc766c4c8ada0de1fb09cb0835b4ea6...  Malware
13457  129568  706af6df0073e41016989080b8ab637e54b0a8ad81010b...  Malware

[13458 rows x 3 columns]

In [28]:
df_test.to_csv("strat_test_1.csv", columns= ['filename', 'Category'], index=False)

In [29]:
df_train.Category.value_counts()

Begnine    103209
Malware      4448
Name: Category, dtype: int64

In [30]:
df_test.Category.value_counts()

Begnine    12902
Malware      556
Name: Category, dtype: int64

In [35]:
df_val = pd.DataFrame(data=cv, index= None, columns=["index"])
df_val = df_val.merge(df2, on = 'index')
df_val

        index                                           filename Category
0      114016  e20bbaa01c8d2efc8bcec3fc246517452002f6d7c1fb2d...  Begnine
1      102585  cb5ffd2419972b339886f2391426cc3ae5ad5e453634af...  Begnine
2       93804  b97a1fb305b387ce361a9cf4d3d5b9d858d011a97024ef...  Begnine
3       35074  4503a83d3f416a06584e058c6aa74a9af3d7560c64c758...  Begnine
4       39844  4e81620e93c9be0dcdedf6994f095e4f9b73694a003607...  Begnine
...       ...                                                ...      ...
13453   31408  3dcd5d4781b04c6bddbd0d1faa3aef703878cf1c1a23f8...  Begnine
13454  112490  defe4f66a3aa793337770c3d89e192d9b26d1264ce1445...  Begnine
13455   48298  5fb16d12bc8a36b9071907bc6e042840c2be62f20201ec...  Begnine
13456   75422  94eb105980f0ba41816b5b4cb73da05d067fb354447321...  Begnine
13457   13644  1aa45e808a328c4f7f9b5397fc074bdf3510f17d9ddd10...  Begnine

[13458 rows x 3 columns]

In [36]:
df_val.to_csv("strat_val_1.csv", columns= ['filename', 'Category'], index=False)

In [37]:
df_val.Category.value_counts()

Begnine    12902
Malware      556
Name: Category, dtype: int64

In [54]:
X = df2.filename
y = df2.Category
g = StratifiedKFold3(10).split(X,y)
train, cv, test = next(g)

####TRAIN######
df_train = pd.DataFrame(data=train, index= None, columns=["index"])
df_train = df_train.merge(df2, on = 'index')
df_train.to_csv("strat_train_10.csv", columns= ['filename', 'Category'], index=False)

####TEST######
df_test = pd.DataFrame(data=test, index= None, columns=["index"])
df_test = df_test.merge(df2, on = 'index')
df_test.to_csv("strat_test_10.csv", columns= ['filename', 'Category'], index=False)

####VALIDATION#####
df_val = pd.DataFrame(data=cv, index= None, columns=["index"])
df_val = df_val.merge(df2, on = 'index')
df_val.to_csv("strat_val_10.csv", columns= ['filename', 'Category'], index=False)